name: zomboid
services:
  zomboid:
    image: "docker.io/renegademaster/zomboid-dedicated-server:latest"
    container_name: ${PROJ_PREFIX}.zomboid
    restart: "unless-stopped"
    ports:
      - "8766:8766/udp"
      - "16261:16261/udp"
      - "16262:16262/udp"
      - "27015:27015/tcp"
    environment:
      - GAME_VERSION=public
      - PAUSE_ON_EMPTY=true
      - PUBLIC_SERVER=true
      - USE_STEAM=true
    env_file:
      - ./.env
      - ./project_zomboid/override.env
    volumes:
      - ${APPDATA}/zomboid/ZomboidDedicatedServer:/home/steam/ZomboidDedicatedServer
      - ${APPDATA}/zomboid/config:/home/steam/Zomboid/
      - ${CONFIGS}/project_zomboid:/home/steam/Zomboid/Server/