name: zomboid
services:
  zomboid:
    build:
      context: project_zomboid
      dockerfile: Dockerfile
      args:
        - USER=$PUID
        - SERVER_BRANCH=42.13.1
    image: "safetycrab/zomboid-dedicated-server:42.13.1"
    container_name: ${PROJ_PREFIX}.zomboid
    restart: "unless-stopped"
    ports:
      - "8766:8766/udp"
      - "16261:16261/udp"
      - "16262:16262/udp"
      - "27015:27015/tcp"
    environment:
      - GAME_VERSION=public
      - PAUSE_ON_EMPTY=true
      - PUBLIC_SERVER=true
      - USE_STEAM=true
    env_file:
      - ./.env
      - ./project_zomboid/override.env
    volumes:
      - ${APPDATA}/zomboid/server-files:/home/steam/projectzomboid
      - ${APPDATA}/zomboid/config:/home/steam/Zomboid/
      # - ${CONFIGS}/project_zomboid:/home/steam/Zomboid/Server/

    # entrypoint: ["tail", "-f", "/dev/null"]
    
