name: matrix
services:
  synapse:
    image: matrixdotorg/synapse:latest
    container_name: matrix.synapse
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_started
    env_file:
      - synapse.env
      - postgres.env
    volumes:
      - $APPDATA/matrix/synapse:/data
    ports:
      - "8008:8008"

  synapse-admin:
    image: awesometechnologies/synapse-admin:latest
    container_name: matrix.synapse-admin
    hostname: synapse-admin
    restart: unless-stopped
    volumes:
      - $APPDATA/matrix/synapse-admin:/data
    ports:
      - "8980:80"

  postgres:
    build:
      context: .
      dockerfile: postgres.Dockerfile
    container_name: matrix.db
    restart: unless-stopped
    env_file:
      - postgres.env
    volumes:
      - $APPDATA/matrix/postgresdata:/var/lib/postgresql/data

  # BRIDGES
  matrix.bridge.whatsapp:
    image: dock.mau.dev/mautrix/whatsapp:latest
    container_name: matrix.bridge.whatsapp
    depends_on:
      matrix.bridge.whatsapp.db:
        condition: service_started
#    user: ${PUID}:${PGID}
    restart: unless-stopped
    volumes:
      - $APPDATA/matrix/bridges/whatsapp/config:/data

  matrix.bridge.whatsapp.db:
    image: postgres:14
    container_name: matrix.bridge.whatsapp.db
    restart: unless-stopped
    env_file:
      - whatsapp-bridge-db.env
    volumes:
      - $APPDATA/matrix/bridges/whatsapp/db:/var/lib/postgresql/data

#  mautrix-discord:
#    image: dock.mau.dev/mautrix/discord:latest
#    container_name: matrix.bridge.discord
##    user: ${PUID}:${PGID}
#    restart: unless-stopped
#    volumes:
#      - $APPDATA/matrix/bridges/discord:/data
#
#  mautrix-googlechat:
#    image: dock.mau.dev/mautrix/googlechat:latest
#    container_name: matrix.bridge.googlechat
##    user: ${PUID}:${PGID}
#    restart: unless-stopped
#    volumes:
#      - $APPDATA/matrix/bridges/gchat:/data

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: "10.0.0.0/24"
          gateway: "10.0.0.1"